### ISSUE TITLE
Downsampling data - nQuack model runs never complete

### ISSUE THREAD

**Issue by RSchley** [mgaynor1/nQuack#5]
Hi there

My nQuack models never end up finishing - the server times out before they finish (after 2 weeks) no matter how much memory or how many processors are thrown at them.

What would be a sensible way of downsampling the data to run nQuack? I am using whole-genome resequencing data at 30x, so individual BAM files are around 30 gigabytes in size.

Thanks so much
Rowan

**Comment by mgaynor1** [comment]
Hi there, this means that the most likely model is not found. The model never converges. 

This could mean many things, for example, you could be including regions with uneven copy number (did you remove repeat regions from your genome?). We found this occurred only when the data was noisy and therefore filtered based on a more stringent mapping quality. 

How large is your reference genome? What is its quality? Is it only a nuclear genome? How well does your WGS data map back to the genome? Do you have secondary alignments (if so, remove these)?

**Comment by RSchley** [comment]
Hi - thanks so much for the answer.

I removed all repeats, filtered with high stringency (depth >5, mapping quality >30). The reference genome is 0.9Gb, is chromosomally contiguous and annotated with high N50 etc (see https://wellcomeopenresearch.org/articles/9-606). I only used the nuclear genome, yes.

WGS data appears to map well to the genome, although the reference is a diploid (but I assume this is the best way forward, since we dont have an allopolyploid reference). I will check about secondary alignments.

**Comment by mgaynor1** [comment]
Well, based on your BUSCO scores, your genome doesn't seem too repetitive or too large. I would guess that you have reads belonging to a different subgenome that are aligning poorly (but this is just a guess).

Since you have a chromosome-level assembly, I recommend splitting your sample by chromosome. You can do this in the 'prepare_data()' step with some modifications to line 30, which I did for you here: https://gist.github.com/mgaynor1/a12584cbe8b722c93e746a513b4c5968

I realized this was not truly chromosome level and that you actually had 401 contigs, so the comment below that gist includes the ability to use a list of contigs. 

Hopefully this helps.

**Comment by RSchley** [comment]
Brilliant - thanks. I will try per-chromosome. Really appreciate the help!

**Comment by mgaynor1** [comment]
Awesome - please reopen this issue if there are any additional questions/concerns. Closing for now!

**Comment by RSchley** [comment]
Hi there and happy new year! Thanks again for writing this function - I was wondering, how do I combine the results per-chromosome to get a 'total' ploidy estimate?

All best
Rowan

**Comment by mgaynor1** [comment]
Hi Rowan, 

To recap: Your data was super noisy and never converged, therefore you split the likelihood estimation into chromosomes. 

To interpret this data in terms of 'total' you would need to run the likelihood calculation for the total data, which cannot be done with your data. Instead, you have many options. For example, you could compare the consistency of the most likely model among chromosomes for each individual. You could also use this approach identify regions to remove in order to have the 'total' estimate converge. 

Good luck.

**Comment by RSchley** [comment]
Brilliant - thanks for the help (as always)! The comparative element would be really interesting for the duplication stuff I'd like to look at in specific chromosomes/regions and would allow me to more effectively leverage the whole-genome data.
